export enum VerifyEmailActionTypes {
  REQUESTED_VERIFY_EMAIL = "REQUESTED_VERIFY_EMAIL",
  RECIVED_VERIFY_EMAIL = "RECIVED_VERIFY_EMAIL",
  FAILED_VERIFY_EMAIL = "FAILED_VERIFY_EMAIL",
}

export enum SignUpActionTypes {
  REQUESTED_SIGNUP = "REQUESTED_SIGNUP",
  RECIVED_SIGNUP = "RECIVED_SIGNUP",
  FAILED_SIGNUP = "FAILED_SIGNUP",
}

export enum LoginActionTypes {
  REQUESTD_LOGIN = "REQUESTD_LOGIN",
  RECIVED_LOGIN = "RECIVED_LOGIN",
  FAILED_LOGIN = "FAILED_LOGIN",
}
